### ISSUE TITLE
FFFS reference incorrect?

### ISSUE THREAD

**Issue by llarsson** [elastisys/security-review#12]
We have gotten the following insightful feedback:

> Såg att ni har en "Cloud Information Security Review Checklist". I main .md så står FFFS 2014:7 som ramverk 1 att följa. Om vi syftar till finansinspektionens föreskrifter så har 2014:7 upphävts helt (konsolideras inte längre) och ersatts sen 2016 med 2015:8 som nu konsoliderats senast med 2020:21. Det var även där regler om ägarledningsprövning och uppdatering i och med penningtvätt gick in.
> 
> Kolla så det inte bara är ett typo :) https://www.fi.se/sv/vara-register/sok-fffs/2015/20158/

Please verify and update as needed.

**Comment by cristiklein** [comment]
Indeed, we were off-by-2. :smile: Nice find! Fixed.
